Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-11, with the labels that each got.

#526 fix: make impact report main story bg white
  package-lock.json
  package.json
  pages/impact/_year/_slug.vue
Labels: fix

#527 fix: APPS-2010 Refactor ES queries
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  package-lock.json
  package.json
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  plugins/data-api.js
  utils/getListingFilters.js
  utils/mergeFilters.js
  utils/searchConfig.js
  utils/sortByTitle.js
Labels: feature

#528 fix: resolve ginny-portrait aspect ratio
  pages/impact/_year/index.vue
Labels: fix

#513 feat: APPS-1967 Create Services and Resources listing page
  cypress/integration/servicesresourceslistpage.spec.js
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  package-lock.json
  package.json
  pages/help/services-resources/index.vue
Labels: feature

#529 fix: remove all overlays from impact banners
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
Labels: fix

#530 feat: adds space between ginny's letter and image
  pages/impact/_year/index.vue
Labels: feature

#531 fix: use askALibrarian global for staff detail page
  pages/about/staff/_slug.vue
Labels: fix

#532 fix: add help topics to services and resources listing
  gql/queries/HelpTopicList.gql
  pages/help/services-resources/index.vue
Labels: fix

#521 feat: Apps 1509 basic event detail page
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  package-lock.json
  package.json
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/events-exhibits/_slug.vue
  plugins/scrape-formid.client.js
Labels: feature

#537 chore: Component library update
  package-lock.json
  package.json
Labels: feature, chore

#538 chore: update components
  package-lock.json
  package.json
Labels: chore

#518 feat: APPS-1947 Create Collections detail page
  cypress/integration/collectiondetailpage.spec.js
  cypress/integration/collectionlistpage.spec.js
  gql/fragments/BlockGridGalleryCardsFragment.gql
  gql/fragments/BlockImpactNumberCardsFragment.gql
  gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
  gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql
  gql/queries/CollectionDetail.gql
  gql/queries/CollectionExploreList.gql
  gql/queries/CollectionsAccessList.gql
  gql/queries/CollectionsList.gql
  gql/queries/PolicyDetail.gql
  pages/about/blogs/_slug.vue
  pages/about/blogs/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/collections/_slug.vue
  pages/collections/explore/index.vue
  pages/collections/index.vue
Labels: feature

#536 feat: adds section wrapper to location detail
  pages/about/news/_slug.vue
  pages/about/programs/_slug.vue
  pages/collections/_slug.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/visit/locations/_slug.vue
Labels: feature

#539 fix: staff-directory-link
  pages/about/programs/_slug.vue
Labels: bugfix

#541 fix: adds external resource with displayEntry true to all services and resources listing page
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  pages/help/services-resources/index.vue
Labels: fix

#535 feat: add site search nuxt route
  cypress/integration/searchsitepage.spec.js
  pages/search_site/index.vue
  plugins/data-api.js
Labels: feature

#544 feat!: APPS-2017 catchglobalqueries
  modules/populate/index.js
  modules/populate/populate.server.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/blogs/_slug.vue
  pages/about/news/_slug.vue
  pages/about/policies/_slug.vue
  pages/about/programs/_slug.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/collections/_slug.vue
  pages/collections/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
  pages/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  store/index.js
Labels: breaking

#545 feat: Event Series Detail Page
  cypress/integration/eventseriesdetail.spec.js
  gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
  gql/queries/EventDetail.gql
  gql/queries/EventWorkshopList.gql
  gql/queries/ExhibitionsAndEventsList.gql
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
Labels: feature

#506 feat: Elastic Search Index plugin
  .github/workflows/ci.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-publish.yml
  gql/queries/ArticleDetail.gql
  gql/queries/CollectionDetail.gql
  gql/queries/EventDetail.gql
  gql/queries/HelpTopicDetail.gql
  gql/queries/ImpactReport.gql
  gql/queries/ImpactReportStory.gql
  gql/queries/LocationDetail.gql
  gql/queries/PolicyDetail.gql
  gql/queries/ProgramDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  gql/queries/StaffDetail.gql
  modules/sitemapRouteGenerator.js
  nuxt.config.js
  pages/_.vue
  pages/about/blogs/_slug.vue
  pages/about/news/_slug.vue
  pages/about/policies/_slug.vue
  pages/about/programs/_slug.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/collections/_slug.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/index.vue
  pages/search_site/index.vue
  pages/visit/locations/_slug.vue
  plugins/data-api.client.js
  plugins/elasticsearchplugin.js
  utils/getListingFilters.js
  utils/searchConfig.js
Labels: Work in progress / Draft ✍, feature

#542 feat: APPS-1966 create listing page for explore collections
  cypress/integration/collectiondetailpage.spec.js
  cypress/integration/collectionsaccesspage.spec.js
  cypress/integration/collectionsexplorepage.spec.js
  gql/queries/CollectionExploreList.gql
  gql/queries/CollectionsAccessList.gql
  gql/queries/CollectionsExploreList.gql
  pages/collections/_slug.vue
  pages/collections/access/index.vue
  pages/collections/explore/index.vue
Labels: feature

#546 fix: update to for search results
  pages/search_site/index.vue
Labels: bugfix

#547 feat: updates general content page with QA
  gql/queries/GeneralContentDetail.gql
  pages/_.vue
Labels: feature

#548 fix: update collections index and collections detail
  gql/queries/CollectionsList.gql
  pages/collections/_slug.vue
  pages/collections/index.vue
Labels: bugfix

#549 fix: help topic page paths
  gql/queries/HelpTopicDetail.gql
  pages/help/_slug.vue
Labels: bugfix

#517 feat: APPS-1964 Create listing page for Collections
  gql/queries/CollectionExploreList.gql
  gql/queries/CollectionsAccessList.gql
  gql/queries/CollectionsList.gql
  pages/collections/access/index.vue
  pages/collections/index.vue
Labels: feature

#510 feat: APPS-1963 create Programs listing page
  cypress/integration/programslistpage.spec.js
  gql/queries/CollectionDetail.gql
  gql/queries/ProgramsList.gql
  pages/about/programs/index.vue
Labels: feature

#514 feat: APPS-1921 Create Policy listing page
  cypress/integration/policieslistpage.spec.js
  gql/fragments/collections/AllFpbWithNoBanner.gql
  gql/queries/PoliciesList.gql
  pages/about/policies/index.vue
  pages/about/programs/index.vue
Labels: feature

#511 feat: APPS-1969 Create News listing page
  cypress/integration/articlenewslistingpage.spec.js
  gql/queries/ArticleList.gql
  pages/about/news/index.vue
Labels: feature

#543 feat: Use upgraded MediaGallery/MediaItem
  gql/fragments/BlockMediaGalleryFragment.gql
  gql/fragments/MediaAsset.gql
  gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql
  package-lock.json
  package.json
Labels: feature

#552 feat: exhibition detail page
  cypress/integration/exhibitiondetail.spec.js
  gql/queries/EventDetail.gql
  pages/visit/events-exhibitions/_slug.vue
Labels: feature

#554 feat: APPS-1731 watch query push router
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  pages/search_site/index.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: feature

#553 feat: APPS-1946 Create Ask Us page template
  cypress/integration/askuspage.spec.js
  gql/queries/AskUs.gql
  pages/help/services-resources/ask-us/index.vue
Labels: Work in progress / Draft ✍, feature

#550 feat: Apps-1949 workshop series detail page
  cypress/integration/generalcontent.spec.js
  cypress/integration/serviceresourcespage.spec.js
  gql/fragments/collections/AllFpbWithNoBanner.gql
  gql/fragments/collections/DefaultFpb.gql
  gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
  gql/fragments/collections/DefaultFpbWithNoCta.gql
  gql/queries/EventDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  package-lock.json
  package.json
  pages/help/services-resources/_slug.vue
Labels: feature

#551 feat: APPS-1970 Create listing page for Endowments
  gql/queries/EndowmentList.gql
  pages/support/endowments/index.vue
  pages/visit/events-exhibitions/_slug.vue
Labels: Work in progress / Draft ✍, feature

#556 feat: Creates endowments detail page
  cypress/integration/endowmentsdetail.spec.js
  gql/fragments/Image.gql
  gql/queries/EndowmentDetail.gql
  pages/support/endowments/_slug.vue
Labels: Work in progress / Draft ✍, feature

#560 feat: updates Ask Us
  pages/help/services-resources/ask-us/index.vue
Labels: feature

#562 fix: mediagallery gql fix for collections detail page
  gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
  gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql
Labels: bugfix

#557 feat: Update sectionhandle query part, Add external resource to index and perform search on search icon button click
  gql/queries/EventDetail.gql
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  package-lock.json
  package.json
  pages/_.vue
  pages/about/staff/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/_slug.vue
  plugins/data-api.js
  plugins/elasticsearchplugin.js
  utils/searchConfig.js
Labels: feature

#559 feat: Create events listing page
  cypress/integration/eventsexhibitionslist.spec.js
  gql/queries/ExhibitionsAndEventsList.gql
  package-lock.json
  package.json
  pages/visit/events-exhibitions/index.vue
Labels: Work in progress / Draft ✍, feature

#563 feat: staff list qa
  gql/queries/StaffList.gql
  pages/about/staff/index.vue
Labels: feature

#558 feat: Create listing page for Student Opportunities
  cypress/integration/jobstudentopportunities.spec.js
  gql/queries/JobStudentOpportunitiesList.gql
  pages/about/student-opportunities/index.vue
Labels: feature

#568 fix: reverted component change version for filters to close when clicked outside and update libcal proxy url
  .env.example
  nuxt.config.js
  package-lock.json
  package.json
Labels: bugfix

#564 feat: use improved MediaWithText
  gql/fragments/BlockMediaWithTextFragment.gql
  gql/fragments/collections/DefaultFpb.gql
  package-lock.json
  package.json
Labels: feature

#569 feat: APPS-1788 fix skip link behavior
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  plugins/add-skip-to.js
Labels: feature

#566 fix: updates from qa of news listing template
  gql/queries/ArticleList.gql
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/help/services-resources/index.vue
Labels: fix
