Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-05, with the labels that each got.

#352 MediaGallery Component
  assets/styles/variables-css.scss
  components/Flexible/MediaGallery.vue
  components/MediaBadge.vue
  components/MediaGallery/BannerImage.vue
  components/MediaGallery/Lightbox.vue
  components/MediaGallery/ThumbnailCard.vue
  stories/Flexible_MediaGallery.spec.js
  stories/Flexible_MediaGallery.stories.js
  stories/MediaBadge.spec.js
  stories/MediaBadge.stories.js
  stories/MediaGallery_BannerImage.spec.js
  stories/MediaGallery_BannerImage.stories.js
  stories/MediaGallery_Lightbox.spec.js
  stories/MediaGallery_Lightbox.stories.js
  stories/MediaGallery_ThumbnailCard.spec.js
  stories/MediaGallery_ThumbnailCard.stories.js
Labels: Questions & || Fixes Requested

#381 APPS-1547 and APPS-1548 BlockStaffDetail and MediaWithText Bugs
  components/BlockStaffDetail.vue
  components/Flexible/MediaWithText.vue
  stories/Flexible_MediaWithText.stories.js
Labels: Ready for Review ​🎯​

#387 fix[component]:Add resize iframe using window post message
  components/BlockHours.vue
  static/blockHours.html
Labels: Ready for Review ​🎯​

#386 APPS-1522 FIX Flexible/MediaWithText Component
  components/BlockMediaWithText.vue
  components/ButtonLink.vue
  components/Flexible/MediaWithText.vue
  components/FlexibleBlocks.vue
  components/SmartLink.vue
  gql/queries/LocationDetail.gql
  gql/queries/ServiceOrResourceDetail.gql
  stories/BlockMediaWithText.stories.js
  stories/Flexible_MediaWithText.spec.js
  stories/Flexible_MediaWithText.stories.js
Labels: Ready for Review ​🎯​

#388 fix[component]: Update SimpleCard with internal resource
  components/SimpleCards.vue
  gql/queries/ServiceOrResourceDetail.gql
  stories/BlockSimpleCard.stories.js
  stories/Flexible_SimpleCards.stories.js
  stories/SimpleCards.spec.js
  stories/SimpleCards.stories.js
  stories/mock-gql.json
Labels: Under Review 👀

#390 style: update styles to current variables
  components/SearchGenericFilterButtons.vue
  components/SearchGenericViewModes.vue
Labels: Under Review 👀

#389 FEAT: Location detail page
  components/BannerText.vue
  components/BlockAmenities.vue
  components/BlockCampusMap.vue
  components/BlockHighlight.vue
  components/BlockHours.vue
  components/BlockSimpleCard.vue
  components/BlockSpaces.vue
  components/DividerGeneral.vue
  components/DividerWayFinder.vue
  components/Flexible/CtaBlockContentWidth.vue
  components/Flexible/SimpleCards.vue
  components/FlexibleBlocks.vue
  components/ModalGeneric.vue
  components/RichText.vue
  components/SectionTeaserCard.vue
  components/SectionTeaserList.vue
  components/SimpleCards.vue
  cypress/integration/locationdetailpage.spec.js
  gql/queries/LocationDetail.gql
  gql/queries/LocationsList.gql
  gql/queries/ServiceOrResourceDetail.gql
  nuxt.config.js
  package-lock.json
  pages/visit/locations/_slug.vue
  stories/BlockHighlight.stories.js
  stories/BlockSpaces.stories.js
  stories/Flexible_CtaBlockContentWidth.stories.js
  stories/Flexible_SimpleCards.stories.js
  stories/SimpleCards.stories.js
  utils/getParentPageTitle.js
Labels: Ready for Review ​🎯​

#395 Integrate MediaGallery into services item page
  components/FlexibleBlocks.vue
  gql/queries/ServiceOrResourceDetail.gql
Labels: Under Review 👀
