Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-10, with the labels that each got.

#492 fix: Apps 1927 get hero image video from craft in impact report main story
  .env.example
  cypress/integration/impactmainstory.spec.js
  gql/fragments/BlockMediaGalleryFragment.gql
  gql/fragments/BlockMediaWithTextFragment.gql
  gql/fragments/collections/ImpactReportFpb.gql
  gql/queries/ImpactReportStory.gql
  pages/impact/_year/_slug.vue
Labels: bugfix

#494 feat: Fix impact report video
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/fragments/BlockMediaWithTextFragment.gql
  gql/queries/ArticleList.gql
  package-lock.json
  package.json
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
Labels: feature

#489 feat: add sectionWrappers
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/index.vue
  pages/visit/events-exhibits/index.vue
Labels: Under Review 👀, feature

#495 fix: impact report - remove truncation of block highlight text and update credit styling
  pages/impact/_year/index.vue
Labels: fix

#496 feat: adds same error page layout used on meap site
  layouts/error.vue
Labels: feature

#497 fix: update impact report query and template to use keyArt field
  gql/queries/ImpactReport.gql
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
Labels: fix

#498 fix: Article Detail Page
  cypress/integration/articleblogdetailpage.spec.js
  cypress/integration/articlenewsdetailpage.spec.js
  gql/queries/ArticleList.gql
  package-lock.json
  package.json
  pages/about/blogs/_slug.vue
  pages/about/blogs/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
Labels: fix

#500 ci: APPS-1935 Add manual site build GH workflow action
  .github/workflows/manual-site-build.yml
Labels: ci

#501 ci: fix syntax
  .github/workflows/manual-site-build.yml
Labels: ci

#499 fix: APPS-1942 Add BlockImpactNumberCardsFragment to AllFpb collection
  gql/fragments/collections/AllFpb.gql
Labels: fix

#502 fix: refactor the bannerText byline
  package-lock.json
  package.json
  pages/about/blogs/_slug.vue
  pages/about/news/_slug.vue
Labels: fix

#504 chore: Apps 1710 update
  data/BlockFormData.json
  package-lock.json
  package.json
  pages/visit/events-exhibits/_slug.vue
Labels: fix

#505 feat: add router anchor nuxt link function
  nuxt.config.js
Labels: feature

#508 refactor: APPS-1988 standardize banner styling on all templates
  layouts/default.vue
  package-lock.json
  package.json
  pages/_.vue
  pages/about/blogs/_slug.vue
  pages/about/news/_slug.vue
  pages/about/policies/_slug.vue
  pages/about/programs/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/impact/_year/_slug.vue
  pages/visit/events-exhibits/_slug.vue
  pages/visit/locations/_slug.vue
Labels: refactor

#516 fix: APPS-1993 impact report animation
  gql/queries/LocationDetail.gql
  pages/impact/_year/index.vue
Labels: bugfix

#509 feat: Apps 1985 libcal proxy url
  nuxt.config.js
  package-lock.json
  package.json
  pages/visit/events-exhibits/_slug.vue
Labels: feature

#507 feat: APPS-1933 Include floating chat widget - LibAnswers to every page
  cypress/integration/homepage.spec.js
  layouts/default.vue
Labels: feature

#519 fix: do not show associated articles block if there are none
  pages/about/programs/_slug.vue
Labels: fix

#520 fix: update banners on impact pages
  package-lock.json
  package.json
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
Labels: bugfix

#515 feat: add nuxt util to scrape formid from public libcal calendar page
  nuxt.config.js
  package-lock.json
  package.json
  pages/visit/events-exhibits/_slug.vue
  plugins/scrape-formid.client.js
  utils/scrapeFormId.js
Labels: feature

#522 feat: APPS-1982 Add ES queries and hook filters on staff and servicesorresources index pages
  data/serviceorresource_entries.json
  data/serviceorresource_test-entries.json
  data/staff_entries.json
  data/staff_test-entries.json
  gql/queries/StaffListwithfulldetail.gql.example
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  pages/index.vue
  plugins/data-api.js
  utils/getListingFilters.js
  utils/searchConfig.js
Labels: feature

#524 fix: add divider before timeline
  pages/impact/_year/index.vue
Labels: fix
