Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-06, with the labels that each got.

#399 feat: Add HeaderMainResponsive to layout
  components/HeaderMain.vue
  components/HeaderMainResponsive.vue
  components/HeaderSmart.vue
  cypress/integration/homepage.spec.js
  cypress/integration/mobilehomepage.spec.js
  layouts/default.vue
  stories/HeaderMainResponsive.stories.js
  stories/HeaderSmart.spec.js
  stories/HeaderSmart.stories.js
Labels: Ready for Review ​🎯​

#400 fix: spacing review with ux team
  components/BannerHeader.vue
  components/BlockMediaWithText.vue
  components/BlockSimpleCard.vue
  components/Flexible/MediaWithText.vue
  components/Flexible/SectionMediaWithText.vue
  components/FlexibleBlocks.vue
  components/RichText.vue
  components/SectionSpacesList.vue
  components/SimpleCards.vue
Labels: Ready for Review ​🎯​

#401 fix: remove blockdivider to match craft updates
  components/Flexible/Divider.vue
  components/FlexibleBlocks.vue
  cypress/integration/locationdetailpage.spec.js
  gql/fragments/BlockDividerFragment.gql
  gql/fragments/collections/AllFpb.gql
  gql/fragments/collections/AllFpbWithNoBanner.gql
  gql/fragments/collections/DefaultFpb.gql
  gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
  gql/fragments/collections/DefaultFpbWithNoCta.gql
  stories/Flexible_Divider.spec.js
  stories/Flexible_Divider.stories.js
Labels: Ready for Review ​🎯​

#402 fix: spacing with ux team
  components/FlexibleBlocks.vue
  components/RichText.vue
Labels: Ready for Review ​🎯​

#405 refactor: instead of doing a function to watch esc key I just used keydown
  components/Flexible/MediaGallery.vue
  components/MediaGallery/NewLightbox.vue
  stories/MediaGallery_Lightbox.spec.js
  stories/MediaGallery_Lightbox.stories.js
Labels: Ready for Review ​🎯​

#407 fix: HeaderMainResponsiveRefactor
  components/HeaderMainResponsive.vue
  components/HeaderSmart.vue
  components/NavMenuItemResponsive.vue
Labels: Ready for Review ​🎯​

#408 feat: assemble article detail page
  components/BannerHeader.vue
  cypress/integration/articledetailpage.spec.js
  gql/fragments/collections/AllFpb.gql
  gql/queries/ArticleBlogDetail.gql
  gql/queries/ArticleNewsDetail.gql
  gql/queries/ArticleNewsList.gql
  pages/about/blog/_slug.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  stories/BannerHeader.stories.js
  utils/getParentPageTitle.js
Labels: Work in progress / Draft ✍

#411 fix: add new fields
  components/BannerHeader.vue
  components/BlockStaffDetail.vue
  components/Flexible/SimpleCards.vue
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/fragments/BlockFormFragment.gql
  gql/fragments/BlockSimpleCardsFragment.gql
  gql/fragments/collections/AllFpb.gql
  gql/fragments/collections/AllFpbWithNoBanner.gql
  gql/fragments/collections/DefaultFpb.gql
  gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
  gql/fragments/collections/DefaultFpbWithNoCta.gql
  gql/queries/ArticleNewsDetail.gql
  gql/queries/LocationDetail.gql
  gql/queries/ServiceOrResourceDetail.gql
  gql/queries/StaffDetail.gql
  pages/about/news/_slug.vue
  pages/about/staff/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/visit/locations/_slug.vue
  stories/BlockSimpleCard.stories.js
  stories/Flexible_SimpleCards.stories.js
  stories/SimpleCards.stories.js
Labels: Ready for Review ​🎯​

#421 chore: Add Github labels that release-drafter will use to decode the version number
  .github/configs/release-drafter.yml
Labels: ci

#422 Fix GH action
  .github/configs/release-drafter.yml
Labels: fix

#425 ci: Add NETLIFY_AUTH_TOKEN this is required for cli login
  .github/workflows/on-publish.yml
Labels: ci

#426 ci: On merge to main github-deployment-environment is set to test
  .github/workflows/ci.yml
Labels: ci

#418 feat: add form fpb
  components/BlockHours.vue
  components/Flexible/Form.vue
  components/FlexibleBlocks.vue
  gql/fragments/FlexibleBlocks.gql
  pages/about/news/_slug.vue
  stories/Flexible_Form.spec.js
  stories/Flexible_Form.stories.js
Labels: Work in progress / Draft ✍, feature

#427 fix: APPS-1653 Update Location template
  components/BannerFeatured.vue
  components/BannerHeader.vue
  components/BannerText.vue
  components/BlockCampusMap.vue
  components/BlockSpaces.vue
  pages/about/news/_slug.vue
  pages/visit/locations/_slug.vue
Labels: fix

#430 fix: on publish GH action will run test with test craft data
  .github/workflows/ci.yml
  .github/workflows/on-publish.yml
  components/MastheadSecondary.vue
  cypress/integration/articledetailpage.spec.js
Labels: bugfix

#431 fix: Add help topics to Services and Resources listing page
  gql/queries/HelpTopicList.gql
  pages/help/services-resources/index.vue
Labels: fix

#433 bugfix: fix form on services and resources page
  gql/fragments/collections/AllFpbWithNoBanner.gql
  gql/fragments/collections/DefaultFpb.gql
  gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql
  gql/fragments/collections/DefaultFpbWithNoCta.gql
  pages/help/services-resources/_slug.vue
Labels: bugfix

#434 fix bug
  gql/fragments/collections/AllFpbWithNoBanner.gql
Labels: fix
