Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-12, with the labels that each got.

#570 fix: Update student-opportunities, add staff-academic-jobs
  cypress/integration/jobopportunitieslist.spec.js
  package-lock.json
  package.json
  pages/about/jobs/job-opportunities/_slug.vue
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/student-opportunities/index.vue
Labels: fix

#512 feat: APPS-1597 Create Location listing page
  gql/queries/LocationsList.gql
  pages/visit/locations/index.vue
  utils/parseAddress.js
  utils/parseAmenities.js
  utils/parseIcons.js
Labels: Work in progress / Draft ✍, feature

#572 fix: skip to main content
  layouts/default.vue
  layouts/impact.vue
  pages/_.vue
  pages/about/blogs/_slug.vue
  pages/about/blogs/index.vue
  pages/about/index.vue.drew.search.example
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/about/policies/_slug.vue
  pages/about/policies/index.vue
  pages/about/programs/_slug.vue
  pages/about/programs/index.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/about/student-opportunities/index.vue
  pages/collections/_slug.vue
  pages/collections/access/index.vue
  pages/collections/explore/index.vue
  pages/collections/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/ask-us/index.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
  pages/impact/all/index.vue
  pages/index.vue
  pages/search-site/index.vue
  pages/support/endowments/_slug.vue
  pages/support/endowments/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/index.vue
  pages/visit/locations/_slug.vue
  pages/visit/locations/index.vue
  store/index.js
Labels: fix

#571 feat: APPS-2011 Add Browseby Last name search on staff and other search fixes
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/_slug.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: feature

#574 fix: add button-more to /collections > News
  gql/queries/CollectionsList.gql
  pages/collections/index.vue
Labels: fix

#575 fix: updates from qa of endowment listing
  cypress/integration/endowmentsdetail.spec.js
  cypress/integration/endowmentslist.spec.js
  package-lock.json
  package.json
  pages/give/endowments/_slug.vue
  pages/give/endowments/index.vue
Labels: Work in progress / Draft ✍, fix

#573 feat: QA on Collection detail and Explore Collections listing
  cypress/integration/collectiondetailpage.spec.js
  gql/queries/CollectionDetail.gql
  gql/queries/CollectionExploreList.gql
  gql/queries/CollectionsList.gql
  pages/collections/explore/_slug.vue
  pages/collections/explore/index.vue
  pages/collections/index.vue
Labels: feature

#576 feat: add 2 spec files and change one file name
  cypress/integration/resource.spec.js
  cypress/integration/service.spec.js
  cypress/integration/workshopseries.spec.js
Labels: test

#579 fix: APPS-2091 update search config with filters for the listing pages.
  cypress/integration/resource.spec.js
  cypress/integration/service.spec.js
  gql/queries/ArticleDetail.gql
  gql/queries/CollectionDetail.gql
  gql/queries/EndowmentDetail.gql
  gql/queries/EventDetail.gql
  pages/collections/explore/_slug.vue
  pages/give/endowments/_slug.vue
  pages/help/services-resources/index.vue
  utils/searchConfig.js
Labels: fix

#578 feat: location listing qa
  package-lock.json
  package.json
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/visit/index.vue
  pages/visit/locations/index.vue
Labels: feature

#581 feat: APPS-2044 Add Single checkbox for subjectlibrarian on staff page
  package-lock.json
  package.json
  utils/searchConfig.js
Labels: feature

#583 feat: APPS-2012 Site Search Pagination
  gql/queries/EndowmentDetail.gql
  pages/give/endowments/_slug.vue
  pages/search-site/index.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: feature

#561 feat: homepage
  cypress/integration/collectiondetailpage.spec.js
  cypress/integration/homepage.spec.js
  gql/queries/EventDetail.gql
  gql/queries/Homepage.gql
  pages/index.vue
  pages/search-site/index.vue
Labels: feature

#584 feat: APPS-2045 group by Academic Depts on staff listing page
  pages/about/staff/index.vue
  utils/flattenTimeLineStructure.js
  utils/searchConfig.js
Labels: feature

#586 fix: Use libcal proxy to avoid CORS issue
  plugins/scrape-formid.client.js
Labels: fix

#582 feat: location detail QA
  gql/queries/LocationDetail.gql
  package-lock.json
  package.json
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/_slug.vue
Labels: feature

#580 feat: APPS-2085 add meta description to templates
  cypress/integration/articleblogslistingpage.js
  cypress/integration/articlenewslistingpage.spec.js
  cypress/integration/eventsexhibitionslist.spec.js
  cypress/integration/impactmainstory.spec.js
  gql/queries/ArticleList.gql
  gql/queries/AskUs.gql
  gql/queries/CollectionsAccessList.gql
  gql/queries/CollectionsList.gql
  gql/queries/EndowmentList.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/HelpTopicDetail.gql
  gql/queries/LocationDetail.gql
  gql/queries/LocationsList.gql
  gql/queries/PoliciesList.gql
  gql/queries/PolicyDetail.gql
  gql/queries/ProgramsList.gql
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  pages/about/blogs/_slug.vue
  pages/about/blogs/index.vue
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/about/policies/_slug.vue
  pages/about/policies/index.vue
  pages/about/programs/_slug.vue
  pages/about/programs/index.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/about/student-opportunities/index.vue
  pages/collections/access/index.vue
  pages/collections/explore/_slug.vue
  pages/collections/explore/index.vue
  pages/collections/index.vue
  pages/give/endowments/_slug.vue
  pages/give/endowments/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/ask-us/index.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
  pages/impact/all/index.vue
  pages/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/_slug.vue
  pages/visit/locations/index.vue
  utils/removeTags.js
Labels: Work in progress / Draft ✍, feature

#587 fix: APPS-2108 Update sectionSummary in BlockMediaGalleryExtraFieldsFragment query
  gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
  package-lock.json
  package.json
Labels: fix

#590 fix: accessibility issues
  cypress/integration/eventseriesdetail.spec.js
  cypress/integration/eventsexhibitionslist.spec.js
  cypress/integration/homepage.spec.js
  gql/queries/EventDetail.gql
  gql/queries/LocationDetail.gql
  layouts/default.vue
  layouts/impact.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/visit/events-exhibitions/_slug.vue
Labels: fix

#588 feat: Library Alerts
  gql/queries/Globals.gql
  layouts/default.vue
  package-lock.json
  package.json
  store/index.js
Labels: feature

#594 fix: Homepage update section dual masonary
  gql/queries/Homepage.gql
  layouts/error.vue
  pages/index.vue
Labels: bugfix
