Repository UCLALibrary/library-website-nuxt, pull requests merged in 2022-09, with the labels that each got.

#470 chore: Update LICENSE
  LICENSE
Labels: chore

#475 fix: update fpb to match structure in craft
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/fragments/BlockSimpleCardsFragment.gql
  package-lock.json
  package.json
Labels: bugfix

#472 feat: add GereralContentPage
  cypress/integration/GeneralContent.spec.js
  cypress/integration/mobilehomepage.spec.js
  gql/queries/GeneralContentDetail.gql
  package-lock.json
  package.json
  pages/_.vue
  plugins/craft.js
  store/index.js
Labels: feature

#478 feat: update component package version
  cypress/integration/GeneralContent.spec.js
  package-lock.json
  package.json
Labels: feature

#479 feat!: dynamic routes for jobs, workshopseries, impact report and main story
  cypress/integration/homepage.spec.js
  cypress/integration/impactmainstory.spec.js
  gql/queries/EventWorkshopList.gql
  gql/queries/ImpactReport.gql
  gql/queries/ImpactReportStory.gql
  gql/queries/ImpactReportsList.gql
  gql/queries/JobsList.gql
  gql/queries/ServiceAndResourceList.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/careers/_slug.vue
  pages/about/careers/index.vue
  pages/about/news/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
  pages/impact/all/index.vue
  pages/visit/events-exhibits/_slug.vue
Labels: breaking

#476 fix: APPS-1510 assemble article detail page
  gql/queries/ArticleBlogDetail.gql
  gql/queries/ArticleDetail.gql
  gql/queries/ArticleList.gql
  gql/queries/ArticleNewsDetail.gql
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/blog/_slug.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
Labels: Work in progress / Draft ✍, fix

#477 feat: Update Location entry to use allFpb flexible page block collection
  gql/fragments/collections/AllFpb.gql
  gql/queries/LocationDetail.gql
Labels: Work in progress / Draft ✍, bugfix

#480 ci: automatically apply linter fixes when possible
  .github/workflows/ci.yml
Labels: ci

#481 fix: APPS-1911 Update Main story template to fetch data from Craft
  gql/queries/ImpactReportStory.gql
  package-lock.json
  package.json
  pages/impact/_year/_slug.vue
Labels: fix

#485 feat: APPS-902 impact report
  cypress/integration/impacthomepage.spec.js
  cypress/integration/impactreportpage.spec.js
  gql/fragments/BlockGridGalleryCardsFragment.gql
  gql/fragments/BlockImpactNumberCardsFragment.gql
  gql/fragments/collections/ImpactReportFpb.gql
  gql/queries/ImpactReport.gql
  package-lock.json
  package.json
  pages/impact/_year/index.vue
  utils/flattenTimeLineStructure.js
  utils/updateImageData.js
Labels: feature

#482 fix: APPS-1713 Add sectionTitle & sectionSummary to FPB collections
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/fragments/BlockBannerFeaturedFragment.gql
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockFormFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/fragments/BlockImpactNumbersCarouselFragment.gql
  gql/fragments/BlockMediaGalleryFragment.gql
  gql/fragments/BlockRichTextFragment.gql
  package-lock.json
  package.json
  pages/index.vue
Labels: fix

#486 chore: update ucla-library-website-components and ucla-library-design…
  cypress/integration/homepage.spec.js
  package-lock.json
  package.json
Labels: chore

#487 feat: Test elastic search api key
  .env.example
  .github/workflows/ci.yml
  .github/workflows/on-publish.yml
  .github/workflows/percy.yml
  nuxt.config.js
  package-lock.json
  pages/index.vue
  plugins/data-api.js
Labels: feature

#490 fix: make es keys optional
  nuxt.config.js
  plugins/data-api.js
Labels: bugfix
