Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-02, with the labels that each got.

#639 fix: article detail page to use category and postdate
  package-lock.json
  package.json
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/impact/all/index.vue
Labels: fix

#638 feat: APPS-2160 registration type, APPS-2182 update search texts, and APPS-2177
  pages/about/index.vue.drew.search.example
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/about/staff/index.vue
  pages/about/student-opportunities/index.vue
  pages/help/services-resources/index.vue
  pages/visit/events-exhibitions/_slug.vue
  plugins/data-api.js
  utils/queryFilterHasValues.js
  utils/searchConfig.js
Labels: feature, bugfix

#641 feat: add site search styling and text
  assets/styles/global.scss
  pages/about/news/index.vue
  pages/search-site/index.vue
Labels: feature

#636 feat: explore collections search and filters
  gql/queries/CollectionsExploreList.gql
  gql/queries/EventDetail.gql
  pages/about/news/index.vue
  pages/collections/explore/index.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: feature

#642 feat: adds ask us summary, updates location banner gradient
  gql/queries/AskUs.gql
  pages/visit/locations/_slug.vue
Labels: feature

#634 feat: Apps 2110 programs filters
  gql/queries/ProgramDetail.gql
  gql/queries/ProgramsList.gql
  pages/about/news/index.vue
  pages/about/programs/_slug.vue
  pages/about/programs/index.vue
Labels: feature

#643 fix: ci swap httpserver with nuxtserver
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  cypress/integration/articlenewsdetailpage.spec.js
  cypress/integration/collectiondetailpage.spec.js
  cypress/integration/endowmentsdetail.spec.js
  cypress/integration/eventseriesdetail.spec.js
  cypress/integration/generalcontent.spec.js
  cypress/integration/helptopicpage.spec.js
  cypress/integration/impactreportpage.spec.js
  cypress/integration/locationdetailpage.spec.js
  cypress/integration/policiesdetailpage.spec.js
  cypress/integration/programdetailpage.spec.js
  cypress/integration/resource.spec.js
  cypress/integration/service.spec.js
  cypress/integration/staffdetailpage.spec.js
  cypress/integration/workshopseries.spec.js
Labels: ci, fix

#644 feat: endowment search filters
  gql/queries/EndowmentList.gql
  pages/give/endowments/_slug.vue
  pages/give/endowments/index.vue
  utils/searchConfig.js
Labels: feature

#640 feat: APPS-2051 add es filters to location and hours listing page
  gql/queries/LocationDetail.gql
  gql/queries/LocationsList.gql
  package-lock.json
  package.json
  pages/about/programs/index.vue
  pages/visit/locations/index.vue
  utils/searchConfig.js
Labels: feature

#646 fix: APPS-2185 Alphabetize Entries on Access Collections Page
  gql/queries/CollectionsAccessList.gql
Labels: fix

#633 feat: credit and link in MediaGallery
  gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
  package-lock.json
  package.json
Labels: feature

#645 fix: Adds netlify redirect file APPS-1991
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  README.md
  cypress.config.js
  cypress.json
  cypress/e2e/articlenewsdetailpage.cy.js
  cypress/e2e/articlenewslistingpage.cy.js
  cypress/e2e/askuspage.cy.js
  cypress/e2e/collectiondetailpage.cy.js
  cypress/e2e/collectionlistpage.cy.js
  cypress/e2e/collectionsaccesspage.cy.js
  cypress/e2e/collectionsexplorepage.cy.js
  cypress/e2e/endowmentsdetail.cy.js
  cypress/e2e/endowmentslist.cy.js
  cypress/e2e/eventseriesdetail.cy.js
  cypress/e2e/eventsexhibitionslist.cy.js
  cypress/e2e/exhibitiondetail.cy.js
  cypress/e2e/generalcontent.cy.js
  cypress/e2e/helptopicpage.cy.js
  cypress/e2e/homepage.cy.js
  cypress/e2e/impactmainstory.cy.js
  cypress/e2e/impactreportpage.cy.js
  cypress/e2e/jobopportunitieslist.cy.js
  cypress/e2e/jobstudentopportunities.cy.js
  cypress/e2e/locationdetailpage.cy.js
  cypress/e2e/mobilehomepage.cy.js
  cypress/e2e/policiesdetailpage.cy.js
  cypress/e2e/policieslistpage.cy.js
  cypress/e2e/programdetailpage.cy.js
  cypress/e2e/programslistpage.cy.js
  cypress/e2e/resource.cy.js
  cypress/e2e/searchsitepage.cy.js
  cypress/e2e/service.cy.js
  cypress/e2e/servicesresourceslistpage.cy.js
  cypress/e2e/staffdetailpage.cy.js
  cypress/e2e/workshopseries.cy.js
  cypress/support/e2e.js
  netlify.toml
  package-lock.json
  package.json
  pages/visit/events-exhibitions/_slug.vue
  static/README.md
  static/_redirects
Labels: fix

#648 fix: use Intl.Collator for sortByTitle
  utils/sortByTitle.js
Labels: fix

#650 fix: APPS-1955 update contributor field query
  pages/about/news/_slug.vue
Labels: fix

#651 fix: APPS-2154 Add space to category in SearchResult component
  pages/search-site/index.vue
Labels: fix

#649 fix: article externalResourceUrl on homepage, program, staff, and collections
  gql/queries/CollectionsList.gql
  gql/queries/ProgramDetail.gql
  gql/queries/StaffDetail.gql
  pages/about/programs/_slug.vue
  pages/about/staff/_slug.vue
  pages/collections/index.vue
  pages/index.vue
Labels: fix

#653 feat: standardize search filter spacing
  assets/styles/global.scss
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/about/staff/index.vue
  pages/collections/access/index.vue
  pages/collections/explore/index.vue
  pages/give/endowments/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/index.vue
  pages/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/index.vue
Labels: feature

#654 fix: update tests and noresults found reset
  cypress/e2e/searchsitepage.cy.js
  cypress/e2e/sitesearch.cy.js
  pages/about/programs/index.vue
  pages/collections/explore/index.vue
  pages/search-site/index.vue
  pages/visit/locations/index.vue
  plugins/data-api.js
Labels: bugfix

#656 fix: update address line breaks
  pages/visit/locations/_slug.vue
  utils/parseAddress.js
Labels: fix

#657 feat: APPS-2142 Update Search placeholders
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/about/staff/index.vue
  pages/collections/explore/index.vue
  pages/give/endowments/index.vue
  pages/help/services-resources/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/index.vue
Labels: feature

#663 fix: deploy prod site from "production" github tag
  .github/workflows/auto-build.yml
Labels: fix

#659 feat: APPS-2159 Replace links with filtered search views endowment detail
  pages/give/endowments/_slug.vue
Labels: feature

#662 fix: add event locations; update locations in news, workshop series, and staff
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  gql/queries/StaffList.gql
  package-lock.json
  package.json
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/about/staff/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
Labels: fix

#655 fix: APPS-2191
  .github/workflows/auto-build.yml
  .github/workflows/ci.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/percy.yml
  cypress/e2e/locationlistpage.cy.js
  modules/indexAliasGenerator.js
  modules/swapAliasIndexGenerator.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/search-site/index.vue
  plugins/data-api.js
  plugins/elasticsearchplugin.js
Labels: ci, bugfix

#658 feat: APPS-2159 Replace location detail staff directory link with filtered search
  pages/visit/locations/_slug.vue
Labels: feature

#661 feat: APPS-2159 feat: Replace links with filtered search views
  package-lock.json
  package.json
  pages/about/programs/_slug.vue
  pages/collections/index.vue
  pages/index.vue
Labels: feature

#664 ci: set "production" tag on release
  .github/workflows/auto-build.yml
  .github/workflows/on-release.yml
Labels: ci

#647 fix: updates events, services, and locations index
  .github/workflows/percy.yml
  cypress/e2e/servicesresourceslistpage.cy.js
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ExhibitionsAndEventsListSingle.gql
  gql/queries/LocationsList.gql
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  pages/index.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/index.vue
  plugins/data-api.js
  static/_redirects
  utils/searchConfig.js
Labels: bugfix

#669 fix: index prefix name in github action
  .github/workflows/ci.yml
  .github/workflows/curltest.yml
  .github/workflows/percy.yml
Labels: bugfix

#668 fix: update services slug page for image logic
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/help/services-resources/_slug.vue
  pages/search-site/index.vue
Labels: bugfix

#670 fix: update ES path with replaceAll
  pages/_.vue
Labels: fix

#672 fix: event series and workshop series associated topic links
  gql/queries/EventDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/help/services-resources/_slug.vue
  pages/visit/events-exhibitions/_slug.vue
Labels: fix

#673 fix: add aliases for collections pages
  pages/collections/access/index.vue
  pages/collections/explore/index.vue
Labels: bugfix

#671 fix: APPS-2202 Further identify the SEE MORE buttons on each page
  pages/about/programs/_slug.vue
  pages/visit/locations/_slug.vue
  pages/visit/locations/index.vue
Labels: fix

#674 fix: trigger auto-build.yml from on-release.yml
  .github/workflows/on-release.yml
Labels: ci, fix

#675 fix: search working, event titles, disappeared events from prod
  gql/queries/EventDetail.gql
  gql/queries/LocationDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  package-lock.json
  package.json
  pages/index.vue
  pages/visit/events-exhibitions/index.vue
  utils/searchConfig.js
Labels: bugfix

#676 fix: APPS-2213 listing page vue node mismatch hydration errors
  cypress/e2e/articlenewslistingpage.cy.js
  cypress/e2e/collectionsexplorepage.cy.js
  cypress/e2e/locationlistpage.cy.js
  cypress/e2e/programslistpage.cy.js
  cypress/e2e/stafflistingpage.cy.js
  nuxt.config.js
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/about/staff/index.vue
  pages/collections/explore/index.vue
  pages/give/endowments/index.vue
  pages/help/services-resources/index.vue
  pages/search-site/index.vue
  pages/visit/locations/index.vue
  plugins/data-api.js
Labels: bugfix

#677 fix: use secrets for sitemap url
  .env.example
  .github/workflows/auto-build.yml
  .github/workflows/ci.yml
  .github/workflows/manual-site-build.yml
  nuxt.config.js
  pages/impact/all/index.vue
Labels: fix

#678 fix: add favicon
  nuxt.config.js
  static/favicon.ico
Labels: fix

#679 ci: deploy to S3
  .github/workflows/auto-build.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
Labels: ci, fix

#681 fix: hard code aws region
  .github/workflows/auto-build.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
Labels: ci, fix

#683 fix: revert s3 deploy and add https to clicc, hours, help
  .github/workflows/auto-build.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
  static/_redirects
Labels: fix

#684 fix: use title or eventTitle on homepage featured events based on sec…
  gql/queries/Homepage.gql
  pages/index.vue
Labels: fix

#686 fix: scroll behaviour when using back/forward browser buttons
  app/router.scrollBehavior.js
  nuxt.config.js
  pages/_.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/about/policies/_slug.vue
  pages/about/programs/_slug.vue
  pages/about/programs/index.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/collections/explore/_slug.vue
  pages/collections/explore/index.vue
  pages/give/endowments/_slug.vue
  pages/give/endowments/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/impact/_year/_slug.vue
  pages/impact/_year/index.vue
  pages/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/_slug.vue
  pages/visit/locations/index.vue
Labels: bugfix

#688 fix: update page title for homepage and error templates
  layouts/default.vue
  layouts/error.vue
Labels: fix

#689 feat: add workshop series to ongoing events section
  gql/queries/ExhibitionsAndEventsList.gql
  pages/visit/events-exhibitions/index.vue
Labels: feature
