Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-04, with the labels that each got.

#695 feat: add new entries to netlify _redirects file and clean it up
  static/_redirects
Labels: feature

#696 fix: index all external resources and only show with displayentry field yes on listing page
  gql/queries/ServiceResourceWorkshopSeriesList.gql
  pages/help/services-resources/index.vue
Labels: bugfix

#697 fix: update eventlocation to location
  .github/workflows/percy.yml
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ExhibitionsAndEventsListSingle.gql
  gql/queries/JobOpportunitiesList.gql
  gql/queries/JobStudentOpportunitiesList.gql
  gql/queries/JobsList.gql
  gql/queries/LocationDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/student-opportunities/index.vue
  pages/visit/events-exhibitions/index.vue
Labels: fix

#700 feat: update general content page label and use featured event series and exhibitions
  gql/queries/ExhibitionsAndEventsListSingle.gql
  pages/collections/access/index.vue
  pages/visit/events-exhibitions/index.vue
Labels: feature

#699 feat: Add type filter to site search
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/about/staff/index.vue
  pages/collections/explore/index.vue
  pages/search-site/index.vue
  pages/visit/locations/index.vue
  plugins/data-api.js
  plugins/elasticsearchplugin.js
  utils/getListingFilters.js
  utils/searchConfig.js
Labels: feature
