Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-07, with the labels that each got.

#711 fix: update component library to 2.37.4
  cypress/e2e/homepage.cy.js
  cypress/e2e/servicesresourceslistpage.cy.js
  package-lock.json
  package.json
  pages/help/services-resources/index.vue
  utils/isRelativeLink.js
Labels: fix

#713 fix: APPS-2375 update component version to 2.37.5
  package-lock.json
  package.json
Labels: bugfix

#712 fix: associated location links from job listings
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/student-opportunities/index.vue
  utils/fixUri.js
Labels: fix, bugfix
