Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-09, with the labels that each got.

#737 feat: APPS-2399 add pinia
  composables/removeEmpties.js
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/queries/EventWorkshopList.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ExhibitionsAndEventsListSingle.gql
  gql/queries/FooterPrimaryItems.gql
  gql/queries/FooterSockItems.gql
  gql/queries/HeaderMainMenuItems.gql
  gql/queries/MenuItems.gql
  layouts/default.vue
  nuxt.config.ts
  package.json
  plugins/init.server.js
  pnpm-lock.yaml
  store/globals.js
Labels: feature

#738 feat: APPS-2425 add craft plugin
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  nuxt.config.ts
  package.json
  plugins/craft.js
  pnpm-lock.yaml
  store/globals.js
Labels: feature

#736 feat: "type" filter for Services & Resources
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: feature

#732 feat: APPS-2054 add search to accessCollections index page
  cypress/e2e/articlenewslistingpage.cy.js
  cypress/e2e/collectionsaccesspage.cy.js
  gql/queries/CollectionsAccessList.gql
  nuxt.config.js
  pages/about/news/_slug.vue
  pages/collections/access/index.vue
  pages/help/services-resources/index.vue
  plugins/elasticsearchplugin.js
  store/index.js
  utils/searchConfig.js
Labels: feature

#739 fix: Add site notification alert to default layout
  .eslintrc
  app.vue
  error.vue
  layouts/default.vue
  layouts/impact.vue
  package.json
  pages/components.vue
  pages/index.vue
  plugins/add-library-website-vue-components.js
  plugins/add-vue-skip-to.js
  plugins/init.server.js
  pnpm-lock.yaml
Labels: fix

#740 fix: APPS-2435
  layouts/impact.vue
  pages/components.vue
  plugins/add-library-website-vue-components.js
  plugins/add-vue-skip-to.js
  plugins/browser-events.client.js
  plugins/craft.js
  plugins/init.server.js
  store/globals.js
Labels: fix

#743 fix: APPS-2422 Change "LIBGUIDE" label on Search Results to "RESEARCH GUIDE"
  package-lock.json
  package.json
  pages/search-site/index.vue
Labels: fix

#741 feat: APPS-1932 Create Media Gallery Half Width component
  gql/fragments/BlockMediaGalleryExtraFieldsFragment.gql
  gql/fragments/BlockMediaGalleryFragment.gql
  pages/collections/explore/_slug.vue
Labels: feature

#744 chore: APPS-2055 Update component library to update richText media embed to include half and full width options
  package-lock.json
  package.json
Labels: chore

#742 fix: APPS-2430 configure ci for nuxt3.x branch
  .eslintignore
  .eslintrc
  .github/configs/release-drafter.yml
  .github/workflows/auto-build.yml
  .github/workflows/ci.yml
  .github/workflows/curltest.yml
  .github/workflows/e2e.yml
  .github/workflows/lint-pr.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
  .github/workflows/percy.yml
  .github/workflows/release-drafter.yml
  .github/workflows/setup-workspace/action.yml
  .gitignore
  app.vue
  composables/removeEmpties.js
  cypress.config.js
  cypress/.eslintrc.json
  cypress/e2e/homepage.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  data/mock-api.json
  error.vue
  layouts/default.vue
  layouts/impact.vue
  nuxt.config.ts
  package.json
  pages/components.vue
  pages/help/index.vue
  pages/index.vue
  plugins/add-library-website-vue-components.js
  plugins/add-vue-skip-to.js
  plugins/browser-events.client.js
  plugins/craft.js
  plugins/init.server.js
  pnpm-lock.yaml
  store/globals.js
Labels: fix
