Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-05, with the labels that each got.

#702 fix: fix events-exhibitions redirect
  static/_redirects
Labels: bugfix

#704 fix: check array length for eventType
  pages/visit/events-exhibitions/index.vue
Labels: bugfix

#703 fix: check length of heroimage array, getting empty array from craft
  cypress/e2e/eventsexhibitionslist.cy.js
  utils/flattenTimeLineStructure.js
Labels: bugfix

#705 fix: APPS-2331 firx breaking "View Article" button for internal links
  gql/queries/Homepage.gql
Labels: fix

#707 fix: APPS-2331
  gql/queries/Homepage.gql
  pages/index.vue
Labels: fix

#709 fix: add forward slash to uri
  utils/flattenTimeLineStructure.js
Labels: bugfix

#708 fix: location links in various pages
  cypress.config.js
  gql/queries/CollectionDetail.gql
  gql/queries/StaffList.gql
  pages/about/staff/index.vue
  pages/collections/explore/_slug.vue
  pages/give/endowments/index.vue
  utils/fixUri.js
Labels: fix, bugfix
