Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-08, with the labels that each got.

#706 feat: APPS-2294 Add PageAnchor to default layout
  app/router.scrollBehavior.js
  cypress/e2e/collectiondetailpage.cy.js
  cypress/e2e/collectionlistpage.cy.js
  cypress/e2e/helptopicpage.cy.js
  cypress/e2e/locationdetailpage.cy.js
  cypress/e2e/policiesdetailpage.cy.js
  cypress/e2e/policieslistpage.cy.js
  cypress/e2e/programdetailpage.cy.js
  cypress/e2e/service.cy.js
  gql/fragments/BlockGridGalleryCardsFragment.gql
  nuxt.config.js
  package-lock.json
  package.json
  pages/_.vue
  pages/about/policies/_slug.vue
  pages/about/policies/index.vue
  pages/about/programs/_slug.vue
  pages/collections/explore/_slug.vue
  pages/collections/index.vue
  pages/help/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/visit/locations/_slug.vue
  plugins/get-headers.client.js
  plugins/scrape-formid.client.js
Labels: feature

#716 fix: APPS-2380_fix-button-banner-header
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  package-lock.json
  package.json
  pages/help/services-resources/_slug.vue
Labels: fix

#718 fix: update component library package version to 2.38.2
  package-lock.json
  package.json
Labels: bugfix

#714 fix: APPS-2300_remove-donor-filter
  package-lock.json
  package.json
  pages/give/endowments/index.vue
Labels: fix

#717 fix: event listing w/ keyword date sort and filter
  pages/visit/events-exhibitions/index.vue
  plugins/data-api.js
  utils/searchConfig.js
Labels: fix, bugfix

#721 fix: APPS-2385 byline error on production news article
  pages/about/news/_slug.vue
Labels: fix

#726 chore: install cypress and configure and test homepage basic test
  cypress.config.js
  cypress/e2e/homepage.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: chore

#727 chore: add eslint
  .eslintrc
  package.json
  pnpm-lock.yaml
Labels: chore

#729 feat: APPS-2383 test local component library
  app.vue
  nuxt.config.ts
  plugins/add-library-website-vue-components.js
Labels: feature

#730 chore: APPS-2402 add global styles and design-token package
  assets/styles/global.scss
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: chore

#728 feat: APPS-2376 & APPS-2328 Add site-search-diacritics & stemming
  modules/indexAliasGenerator.js
Labels: feature

#731 fix: APPS-2403 buttonurl is not required if the program URL behaviour is external
  pages/about/programs/index.vue
Labels: bugfix

#734 chore: APPS-2398 add layouts
  app.vue
  data/mock-api.json
  layouts/default.vue
  layouts/error.vue
  layouts/impact.vue
  nuxt.config.ts
  package.json
  pages/components.vue
  plugins/add-vue-skip-to.js
  pnpm-lock.yaml
Labels: chore

#733 fix: vue redirect for /impact/all
  pages/impact/all.vue
Labels: bugfix

#735 fix: APPS-2420 return correct parseURL on event detail
  pages/visit/events-exhibitions/_slug.vue
Labels: fix
