Repository UCLALibrary/library-website-nuxt, pull requests merged in 2023-01, with the labels that each got.

#585 fix: events templates qa
  gql/queries/ExhibitionsAndEventsList.gql
  layouts/default.vue
  layouts/impact.vue
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
Labels: fix

#599 fix: update styling of block hours
  package-lock.json
  package.json
  static/blockCliccHours.html
  static/blockHours.html
Labels: fix

#603 feat: APPS-2023 amentities location detail
  cypress/integration/eventsexhibitionslist.spec.js
  gql/queries/LocationDetail.gql
  package-lock.json
  pages/visit/locations/_slug.vue
  pages/visit/locations/index.vue
Labels: feature

#597 feat: programs QA
  gql/queries/ProgramsList.gql
  pages/about/programs/_slug.vue
  pages/about/programs/index.vue
  pages/visit/locations/_slug.vue
Labels: feature

#598 feat: add featured endowments section to endowment listing
  gql/queries/EndowmentList.gql
  pages/give/endowments/index.vue
Labels: feature

#605 chore: update component library
  package-lock.json
  package.json
Labels: chore

#604 fix: find general content pages by full uri path
  .github/workflows/ci.yml
  gql/queries/GeneralContentDetail.gql
  pages/_.vue
  plugins/elasticsearchplugin.js
Labels: fix

#607 chore: update component library 2.25.3
  cypress/integration/homepage.spec.js
  package-lock.json
  package.json
  pages/about/staff/index.vue
Labels: chore

#606 fix: window.innerWidth in Chrome devtools
  nuxt.config.js
Labels: fix

#600 feat: add series and exhibitions to event listing
  gql/queries/EndowmentList.gql
  gql/queries/ExhibitionsAndEventsList.gql
  pages/visit/events-exhibitions/index.vue
Labels: feature

#608 feat: APPS 2149 add date components
  gql/queries/CollectionsAccessList.gql
  gql/queries/CollectionsExploreList.gql
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/about/news/_slug.vue
  pages/help/services-resources/_slug.vue
  pages/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
Labels: feature

#612 fix: link URL in BlockCallToAction
  gql/fragments/BlockCallToActionFragment.gql
Labels: fix

#614 feat: add related series to event and workshop detail
  gql/queries/EventDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/help/services-resources/_slug.vue
  pages/index.vue
  pages/search-site/index.vue
  pages/visit/events-exhibitions/_slug.vue
Labels: feature

#611 fix: alternativeName in endowment detail title
  package-lock.json
  package.json
  pages/give/endowments/_slug.vue
  pages/give/endowments/index.vue
Labels: fix

#618 feat: update location detail
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/JobOpportunitiesList.gql
  gql/queries/JobStudentOpportunitiesList.gql
  gql/queries/JobsList.gql
  gql/queries/LocationDetail.gql
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/about/programs/index.vue
  pages/about/student-opportunities/index.vue
  pages/help/services-resources/_slug.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/locations/_slug.vue
Labels: feature

#619 feat!: APPS-2049 APPS-2118 add ES filters to news index and Use ES Alias
  .github/workflows/ci.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-publish.yml
  .github/workflows/percy.yml
  cypress/integration/articleblogdetailpage.spec.js
  cypress/integration/articleblogslistingpage.js
  gql/queries/ArticleDetail.gql
  layouts/default.vue
  modules/indexAliasGenerator.js
  modules/sitemapRouteGenerator.js
  modules/swapAliasIndexGenerator.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/blogs/_slug.vue
  pages/about/blogs/index.vue
  pages/about/news/index.vue
  pages/about/staff/index.vue
  pages/index.vue
  plugins/elasticsearchplugin.js
  plugins/scrape-formid.client.js
  store/index.js
  utils/scrapeFormId.js
  utils/searchConfig.js
Labels: feature, bugfix, breaking

#617 feat: adds new fields in event detail query to determine event registration type
  gql/queries/EventDetail.gql
Labels: feature

#620 feat: updates site search ask us link, adds job listing payrate
  cypress/integration/homepage.spec.js
  gql/queries/JobOpportunitiesList.gql
  pages/about/jobs/staff-academic-jobs/index.vue
  pages/search-site/index.vue
Labels: feature

#621 chore: update component library and queries
  gql/fragments/BlockBannerFeaturedFragment.gql
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  package-lock.json
  package.json
  pages/impact/_year/_slug.vue
Labels: chore

#622 fix: APPS-2163 Update component version to replace craft url, fix nuxt error and news categories
  package-lock.json
  package.json
  pages/about/news/index.vue
Labels: bugfix

#623 fix: listing pages with fetch hook will be indexed when fetchonserver prop is turned on
  pages/about/news/index.vue
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
Labels: bugfix

#625 fix: libcal hours display
  package-lock.json
  package.json
  pages/visit/locations/index.vue
Labels: bugfix

#626 fix: fix partial indexing issue
  modules/indexAliasGenerator.js
  modules/swapAliasIndexGenerator.js
  pages/about/news/index.vue
  pages/about/staff/index.vue
  pages/help/services-resources/index.vue
  plugins/elasticsearchplugin.js
Labels: bugfix

#627 fix: Fix "ongoing" in Exhibitions
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/LocationDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/visit/locations/_slug.vue
Labels: bugfix

#624 feat: workshop and event QA
  gql/queries/EventDetail.gql
  gql/queries/ServiceOrResourceOrWorkshopDetail.gql
  pages/help/services-resources/_slug.vue
  pages/help/services-resources/index.vue
  pages/visit/events-exhibitions/_slug.vue
  pages/visit/events-exhibitions/index.vue
  pages/visit/locations/_slug.vue
Labels: feature

#630 fix: use valid HTML for hours and fix styling
  static/blockCliccHours.html
  static/blockHours.html
Labels: fix

#632 feat: Add router-extras package
  nuxt.config.js
  pages/help/_slug.vue
  pages/help/services-resources/ask-us/index.vue
Labels: feature

#628 ci: build prod site daily
  .github/workflows/auto-build.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/ci.yml
  .github/workflows/on-publish.yml
Labels: ci

#635 fix: update event detail and listing page queries to use eventTitle as title
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
Labels: fix

#637 ci: fix daily build workflow
  .github/workflows/auto-build.yml
  .github/workflows/manual-site-build.yml
Labels: ci
