Repository UCLALibrary/library-website-nuxt, pull requests merged in 2024-10, with the labels that each got.

#860 feat: Add rich text fragment to impact report FBP query
  gql/fragments/collections/ImpactReportFpb.gql
Labels: feature

#861 fix: time on homepage
  package.json
  pnpm-lock.yaml
Labels: fix

#863 feat: APPS-2939 delete old indices on new create
  README.md
  modules/finalize.js
  router.options.ts
Labels: feature

#864 feat: upgrade nuxt version and component version
  .github/workflows/setup-workspace/action.yml
  package.json
  pnpm-lock.yaml
Labels: feature, enhancement, performance, refactor

#862 fix: APPS-2903 Create a redirect for staff subject librarian
  middleware/redirect.global.js
  netlify.toml
Labels: fix

#859 feat: status page with libguides integration on client side
  .github/workflows/setup-workspace/action.yml
  netlify/edge-functions/blockUserAgents.js
  nuxt.config.ts
  package.json
  pages/about/status-updates.vue
  pnpm-lock.yaml
Labels: feature
