Repository UCLALibrary/library-website-nuxt, pull requests merged in 2024-06, with the labels that each got.

#830 refactor: APPS-2728 Clean URL for ServicesResources
  cypress/e2e/servicesresourceslistpage.cy.js
  pages/help/services-resources/index.vue
Labels: refactor

#831 fix: APPS-2729 update search site query
  pages/search-site/index.vue
Labels: fix

#832 refactor: APPS-2730 create clean search url for events exhibition
  cypress/e2e/eventsexhibitionslist.cy.js
  pages/visit/events-exhibitions/index.vue
Labels: refactor

#835 fix: add ref value for the footer
  stores/GlobalStore.js
Labels: bugfix

#834 fix: APPS-2761 replace old link format
  pages/about/programs/[slug].vue
  pages/visit/locations/[slug].vue
  public/_redirects
Labels: fix
