Repository UCLALibrary/library-website-nuxt, pull requests merged in 2024-03, with the labels that each got.

#766 fix: es temp index env for libguides tem prefix is added now
  .github/workflows/auto-build.yml
Labels: ci, bugfix

#767 feat: APPS-2585 Add News Slug Listing pages
  cypress/e2e/articlenewsdetailpage.cy.js
  cypress/e2e/articlenewslistingpage.cy.js
  gql/queries/ArticleDetail.gql
  gql/queries/ArticleList.gql
  layouts/default.vue
  package.json
  pages/about/news/[slug].vue
  pages/about/news/index.vue
  pages/about/reports/news/[slug].vue
  pages/about/reports/news/index.vue
  pnpm-lock.yaml
  utils/getListingFilters.js
  utils/queryFilterHasValues.js
  utils/searchConfig.js
Labels: feature

#772 ci: fix cypress binary error
  .github/workflows/setup-workspace/action.yml
Labels: ci

#773 ci: Fix percy token name for nuxt3
  .github/workflows/percy.yml
Labels: ci

#774 ci: Fix add percy branch for the token
  .github/workflows/percy.yml
Labels: ci

#776 fix: font errors
  nuxt.config.ts
  pages/about/news/index.vue
  pages/impact/[year]/index.vue
Labels: bugfix

#777 fix: add redirect to subject librarian
  cypress/e2e/collectiondetailpage.cy.js
  cypress/e2e/eventseriesdetail.cy.js
  static/_redirects
Labels: fix
