Repository UCLALibrary/library-website-nuxt, pull requests merged in 2024-01, with the labels that each got.

#757 fix: remove * postfix for fuzzy searches
  cypress/e2e/homepage.cy.js
  plugins/data-api.js
Labels: bugfix

#758 fix: replace main with nuxt3.x to be deployed to nuxt3.x netlify site when pull request is merged to nuxt3.x
  .github/workflows/ci.yml
Labels: ci, fix

#759 fix: ci update publish directory
  .github/workflows/ci.yml
Labels: ci, fix

#762 style: APPS-2536 LibCal/Hours website widget formatting
  static/blockCliccHours.html
  static/blockHours.html
Labels: fix, bugfix

#761 fix: update search via clear button (components update)
  package-lock.json
  package.json
Labels: fix
