Repository UCLALibrary/library-website-nuxt, pull requests merged in 2024-05, with the labels that each got.

#796 feat: APPS-2661 Add programs slug page
  cypress/e2e/programdetailpage.cy.js
  gql/queries/CollectionsExploreList.gql
  gql/queries/ProgramDetail.gql
  package.json
  pages/about/programs/[slug].vue
  pnpm-lock.yaml
Labels: feature

#794 feat: APPS-2659 enable preview mode collections actions index, APPS-2656 enable ES
  cypress/e2e/collectionsaccesspage.cy.js
  gql/queries/CollectionDetail.gql
  gql/queries/CollectionsAccessList.gql
  gql/queries/LocationDetail.gql
  modules/init.js
  nuxt.config.ts
  pages/collections/access/index.vue
  pages/visit/events-exhibitions/[slug].vue
  plugins/data-api.js
  plugins/indexer.server.js
  utils/searchConfig.js
Labels: feature

#797 feat: APPS-2655 Enable ES on Endowments Listing page
  cypress/e2e/endowmentslist.cy.js
  pages/about/news/index.vue
  pages/collections/access/index.vue
  pages/give/endowments/index.vue
Labels: feature

#800 feat: APPS-2654 Enable ES on Events Listing page
  cypress/e2e/eventsexhibitionslist.cy.js
  pages/visit/events-exhibitions/index.vue
Labels: feature

#802 fix: APPS-2664 Remove query portion that is not required
  gql/fragments/BlockImpactNumberCardsFragment.gql
Labels: bugfix

#799 feat: APPS-2653 Enable ES Location Listing page
  cypress/e2e/locationlistpage.cy.js
  pages/visit/locations/index.vue
Labels: feature

#803 fix: cypress errors on nuxt3 percy check
  .github/workflows/percy.yml
  cypress/e2e/endowmentslist.cy.js
  cypress/e2e/eventsexhibitionslist.cy.js
  cypress/e2e/locationlistpage.cy.js
Labels: chore, ci, fix

#801 feat: APPS-2662 Migrate search-site template
  .github/workflows/auto-build.yml
  .github/workflows/ci.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
  .github/workflows/percy.yml
  cypress/e2e/collectionsaccesspage.cy.js
  cypress/e2e/eventsexhibitionslist.cy.js
  cypress/e2e/sitesearch.cy.js
  modules/init.js
  nuxt.config.ts
  package.json
  pages/search-site/index.vue
  pages/visit/locations/[slug].vue
  plugins/indexer.server.js
  pnpm-lock.yaml
  server/api/fetchTempIndexName.js
Labels: feature

#804 feat: APPS-2666 Migrate slug/detail template to nuxt3.x for route /about/staff/[slug].vue
  cypress/e2e/staffdetailpage.cy.js
  gql/queries/StaffDetail.gql
  package.json
  pages/about/staff/[slug].vue
  pnpm-lock.yaml
Labels: feature

#806 feat: APPS-2676
  cypress/e2e/user_agent_spec.js
  netlify.toml
  netlify/edge-functions/blockUserAgents.js
  static/robots.txt
Labels: feature

#807 feat: Apps-2660 Migrate about/programs index page template to nuxt3 branch
  cypress/e2e/programslistpage.cy.js
  gql/queries/ProgramsList.gql
  pages/about/programs/index.vue
Labels: feature

#798 feat: APPS-2652 Enable Elastic Search on Services & Resources listing page
  cypress/e2e/servicesresourceslistpage.cy.js
  nuxt.config.ts
  package.json
  pages/collections/access/index.vue
  pages/help/services-resources/index.vue
  pnpm-lock.yaml
Labels: feature

#808 chore: APPS-2678 Update nuxt3.x branch with the new changes in main
  cypress/e2e/user_agent_spec.js
  netlify.toml
  netlify/edge-functions/blockUserAgents.js
  static/robots.txt
Labels: chore

#809 feat: APPS-2669 Add ES to staff-listing template
  .github/workflows/manual-site-build-nuxt3x.yml
  cypress/e2e/stafflistingpage.cy.js
  gql/queries/StaffList.gql
  package.json
  pages/about/staff/index.vue
  plugins/data-api.js
  pnpm-lock.yaml
  utils/getListingFilters.js
Labels: feature

#805 feat: APPS-2658 Migrate collections/explore index page template to nuxt3
  cypress/e2e/collectionsexplorepage.cy.js
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  pages/about/news/index.vue
  pages/collections/access/index.vue
  pages/collections/explore/index.vue
  pages/help/services-resources/index.vue
Labels: feature

#810 feat: APPS-2682 add retries to cypress tests
  .github/workflows/auto-build.yml
  .github/workflows/ci.yml
  .github/workflows/manual-site-build-nuxt3x.yml
  .github/workflows/manual-site-build.yml
  .github/workflows/on-release.yml
  .github/workflows/percy.yml
  cypress.config.js
Labels: feature

#811 chore: APPS-2714 Move Robot.txt file
  public/_redirects
  public/blockCliccHours.html
  public/blockHours.html
  public/robots.txt
Labels: chore

#812 chore: APPS-2712 Add GoogleTagsManager to Nuxt3
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: chore

#813 chore: APPS-2716 Update Nuxt3 config
  app.vue
  nuxt.config.ts
  pages/collections/explore/index.vue
Labels: chore

#815 fix: APPS-2682 intercept and wait on flaky tests
  cypress/e2e/articlenewslistingpage.cy.js
  cypress/e2e/collectionsexplorepage.cy.js
  cypress/e2e/eventsexhibitionslist.cy.js
  cypress/e2e/policiesdetailpage.cy.js
Labels: fix

#816 ci: Create nuxt3x.yml
  .github/workflows/nuxt3x.yml
Labels: ci

#814 fix: Update component library & fpb banner featured query to correspond with component PR 513
  gql/fragments/BlockBannerFeaturedFragment.gql
  package.json
  pages/index.vue
  pnpm-lock.yaml
Labels: fix

#817 fix: APPS-2722 fix section-wrapper vshow statement on staff listing page
  pages/about/staff/index.vue
Labels: bugfix

#820 fix: APPS-2721 fix past events filter
  pages/visit/events-exhibitions/index.vue
Labels: fix

#819 fix: APPS-2711 Fix Vue-Skip-To in Nuxt3
  app.vue
  layouts/default.vue
  package.json
  pnpm-lock.yaml
Labels: fix

#823 ci: update nuxt3x.yml
  .github/workflows/nuxt3x.yml
Labels: ci

#824 ci: Update nuxt3x.yml
  .github/workflows/nuxt3x.yml
Labels: ci

#825 ci: Update nuxt3x.yml
  .github/workflows/nuxt3x.yml
Labels: ci

#822 fix: APPS-2725 queries on news page
  cypress/e2e/locationlistpage.cy.js
  cypress/e2e/programslistpage.cy.js
  pages/about/news/index.vue
  pages/about/programs/index.vue
  pages/visit/locations/index.vue
  utils/parseFilters.js
Labels: fix

#827 Create output.yml
  .github/workflows/output.yml
Labels: chore

#829 chore: delete the file
  .github/workflows/output.yml
Labels: chore

#821 refactor: APPS-2726 create clean search url for staff
  cypress/e2e/stafflistingpage.cy.js
  pages/about/staff/index.vue
Labels: refactor

#826 refactor: APPS-2727 Clean URL for CollectionsExplore
  .gitignore
  cypress/e2e/collectionsexplorepage.cy.js
  pages/collections/explore/index.vue
Labels: refactor
