Repository UCLALibrary/library-website-nuxt, pull requests merged in 2025-01, with the labels that each got.

#870 fix: add redirect
  public/_redirects
Labels: bugfix

#871 fix: remove library.ucla.edu/givemusic and remove a trailing slash
  public/_redirects
Labels: enhancement

#872 feat: APPS-3143 website URL redirect
  public/_redirects
Labels: feature
