Repository UCLALibrary/library-website-nuxt, pull requests merged in 2025-05, with the labels that each got.

#880 feat: APPS-3276 remove past events filter and disable aggregation in keyword search query
  composables/useSearch.ts
  pages/visit/events-exhibitions/index.vue
Labels: feature, bugfix

#882 feat: Add search to Nav
  .github/workflows/ci.yml
  composables/useSearch.ts
  modules/init.js
  package.json
  pages/search-site/index.vue
  pnpm-lock.yaml
Labels: feature

#881 feat: APPS-3300 Add new redirect for /about/programs/books-open-access-boa-pilot-program
  public/_redirects
Labels: feature

#883 fix: update link to staff page to use uri from query
  pages/visit/events-exhibitions/[slug].vue
Labels: bugfix
